### ISSUE TITLE
Atl03Reader, Atl03BathyReader polyregion function may have an incorrect check for full extent found

### ISSUE THREAD

**Issue by elidwa** [SlideRuleEarth/sliderule#412]
/* If Coordinate Is NOT In Polygon */
if(!inclusion && segment_ph_cnt[segment] != 0)
 {
        break; // full extent found!
 }

If segment is not in the polygon (inclusion == FALSE) there is no need to check if segments ph cnt is zero or not. Code should only check for inclusion. Before changing JP needs to verify if there was a reason for this check, if there was, please document in code.

**Comment by elidwa** [comment]
![extrasegments](https://github.com/SlideRuleEarth/sliderule/assets/109287568/21b2bdae-95ea-4fe2-bbe0-e1922264480a)
![correctsegments](https://github.com/SlideRuleEarth/sliderule/assets/109287568/4fcd01f6-0ae5-4953-b4c9-0c1d6124a80e)

Added two screen shots of plots. In one Atl03Viewer has extra segments outside of the bbox. That was due to the wrong check for full extent found. The second screenshot has only segments contained in the bbox. Notice that at the time Atl03Viewer implementation used the same polyregion function as Atl03Reader and BathyReader. This is no longer the case. Atl03Viewer has simplified polyregion implementation.

**Comment by jpswinski** [comment]
The photon count for the segment being zero is a special case in the ATL03 data and those segments must be ignored.  There are cases when a zero-count segment has a bogus latitude and longitude - therefore using those segments to determine inclusion inside a polygon can prematurely treat the track as having entered or exited the polygon.

Therefore the code is correct as is.

**Comment by elidwa** [comment]
Comment was added on branch: allrowsfix, pull request:  #414
